### ISSUE TITLE
Could not start ActiveDesktop

### ISSUE THREAD

**Issue by nicof38** [AndreasVerhoeven/AveActiveDesktop#1]
Hi,

When running this app on a freshly setup windows 7 64bits, I get the "Could not start ActiveDesktop" error message when clicking on "Start ActiveDesktop".

I have tried to install VC++ Redistributable Package (x64) but still the same error. Is there any others dependencies for this one ?

Thanks

**Comment by AndreasVerhoeven** [comment]
What kind of file are you trying to use as background?

**Comment by nicof38** [comment]
Basic html file which is working fine with your app on my development machine. So should be an issue with a depedency but don't know what is needed by this app ?

**Comment by nicof38** [comment]
For now, I have found this workaround:
  1 use a local HTML file first
  2 if still receiving the error (using vbs of start active desktop) go to 3, else 4
  3 reboot machine
  4 use any html file (through HTTP or local file)

**Comment by AndreasVerhoeven** [comment]
The error means it can't find the desktop. If you put focus on the desktop, does that help?

**Comment by nicof38** [comment]
For now, it is installed and working after a first reboot on my 3 PCs, so cannot reproduce it anymore.
I will let u know if I can test it on a new machine.

Anyway, congrats for this one, works very well !

**Comment by AndreasVerhoeven** [comment]
That's good to hear!

**Comment by NTheZone** [comment]
The workaround did not work for me.  Same system config's as OP on a new machine.  Any suggestions?

**Comment by AndreasVerhoeven** [comment]
Do you run the x64 or x32 version?

**Comment by NTheZone** [comment]
Hello Andreas,

Thank you for following up.  I am running the 64-bit version, Win7Pro 64-bit.  Mostly a brand-new 
machine, a Lenovo T460s, with a lot of OEM-installed software removed.  I also tried AveDesktopSites 
but also to no avail.  It said something about not being able to hook, even though I had place 
desktophook.dll in c:\windows\system32

FWIW, I also have a DisplayLink USB driver installed, but installed and tried both programs without 
the external USB monitor attached (Asus 168B+)

Lastly, I would LOVE to have this as my desktop background -- http://earth.nullschool.net/

Let me know, what I can do to help.

Best regards, and thanks for your work.
Raj

**Comment by AndreasVerhoeven** [comment]
Windows 10?

**Comment by NTheZone** [comment]
Hi Andreas,

I have not tried Windows 10.  For various version control reasons and (legacy scientific CAD and 
drivers for electronic equipment reason), I have not made that transition.

Raj

**Comment by AndreasVerhoeven** [comment]
Are you running on 7 or 8 then? :)

**Comment by NTheZone** [comment]
From my post a few days ago, I noted, "I am running the 64-bit version, Win7Pro 64-bit. Mostly a 
brand-new machine, a Lenovo T460s, with a lot of OEM-installed software removed."

It is the same version that was used by the OP.
